services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: review-assign-service-db
    expose:
      - "5432"
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U user -d review-assign-service-db'"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s
    networks:
      - internal-test

  avito-review-assign-service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.example
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 2s
    networks:
      - internal-test

  tests:
    build: 
      context: .
      dockerfile: ./e2e_tests/Dockerfile
    depends_on:
      avito-review-assign-service:
        condition: service_healthy
    environment:
      API_URL: http://avito-review-assign-service:8080
    networks:
      - internal-test

networks:
  internal-test:
