services:

  # avito-review-assign-service:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file: .env
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   networks:
  #     - internal

  postgres:
    image: postgres:16-alpine
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - review_assign_service_data:/var/lib/postgresql/data
    # healthcheck:
    #       test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d shop'"]
    #       interval: 5s
    #       timeout: 10s
    #       retries: 5
    #       start_period: 10s
    networks:
      - internal

networks:
  internal:

volumes:
  review_assign_service_data: